version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/nextjs/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/strapi/"
    schedule:
      interval: "daily"
