version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/nextjs/"
    schedule:
      interval: "daily"
    labels:
      - "nextjs"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/strapi/"
    schedule:
      interval: "daily"
    labels:
      - "strapi"
      - "dependencies"
