yarnPath: ".yarn/releases/yarn-berry.js"

packageExtensions:
  strapi@*:
    peerDependencies:
      strapi-admin: "*"
      strapi-connector-bookshelf: "*"
      strapi-plugin-content-manager: "*"
      strapi-plugin-content-type-builder: "*"
      strapi-plugin-email: "*"
      strapi-plugin-upload: "*"
      strapi-plugin-users-permissions: "*"
      strapi-utils: "*"
  strapi-database@*:
    peerDependencies:
      strapi-connector-bookshelf: "*"
  strapi-connector-bookshelf@*:
    peerDependencies:
      sqlite3: "*"
      pg: "*"
  grant@*:
    dependencies:
      koa: "*"