version: "3.8"
services:
  strapi:
    image: docker.pkg.github.com/mdcuresearchclub/web/strapi
    networks:
      - default
      - main
    env_file:
      - .env.strapi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337"]
      interval: 1m
      timeout: 5s

  postgres:
    image: postgres
    env_file:
      - .env.postgres
    volumes:
      - strapi-postgres:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  strapi-postgres:

networks:
  main:
    external: true
    name: Main_default
